project_id = "wrxddctlyyiqgetiwdpu"

[functions.sync-coupon]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-seed]
verify_jwt = false
